### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by manjunathhegden** [bionictoucan/Slic#4]
I have downloaded Slic and tried to run ..but getting error. 
python data.py --dataset "/home/manjunath/Downloads/Slic/example_data/" --percent_split 10 --save_dir "/home/manjunath/"
getting below error : 

Traceback (most recent call last):
  File "data.py", line 63, in <module>
    train_test_data(dataset=args.dataset,percentage_split=args.percent_split,save_dir=args.save_dir)
  File "data.py", line 28, in train_test_data
    data_list = sorted([direc+"/"+x for x in os.listdir(direc) if not x.startswith(".")])
NotADirectoryError: [Errno 20] Not a directory: '/home/manjunath/Downloads/Slic/example_data/FG20111008_111533.0.fits.gz'

**Comment by besmaguesmi** [comment]
@manjunathhegden  create a new folder inside "exemple_data" folder and then move on all the files from "exemple_data" folder to "exemple_data/data" folder
